---
- name: "openbsd : apply base role to all"
  hosts: all
  become: true
  become_method: doas
  become_user: root
  roles:
    - role: base
  tags:
    - xray
    - ocserv
    - sshvpn
    - hysteria
    - dns

- name: "openbsd : setup ocserv"
  hosts: ocserv, all_vpns
  become: true
  become_method: doas
  become_user: root
  roles:
    - role: ocserv
  tags:
    - ocserv

- name: "openbsd : setup xray vpn"
  hosts: vless, vmess, trojan, all_vpns
  become: true
  become_method: doas
  become_user: root
  roles:
    - role: xray
  tags:
    - xray

- name: "openbsd : setup sshvpn"
  hosts: sshvpn, all_vpns
  become: true
  become_method: doas
  become_user: root
  roles:
    - role: sshvpn
  tags:
    - sshvpn

- name: "openbsd : setup sshvpn"
  hosts: hysteria, all_vpns
  become: true
  become_method: doas
  become_user: root
  roles:
    - role: hysteria
  tags:
    - hysteria

- name: "openbsd : setup dns resolver with adblock and web interface"
  hosts: all
  become: true
  become_method: doas
  become_user: root
  roles:
    - role: dns
#    - role: web
  tags:
    - xray
    - ocserv
    - sshvpn
    - hysteria
    - dns

#  - name: "openbsd : setup web interface for vpn clients"
#    hosts: all
#    become: true
#    become_method: doas
#    become_user: root
#    roles:
#      - role: web
#    tags:
#      - web
#
