---
- name: "openbsd : apply base role to all"
  hosts: all
  roles:
    - role: base
  tags:
    - base

- name: "openbsd : setup ocserv"
  hosts: ocserv, all_vpns
  roles:
    - role: ocserv
  tags:
    - ocserv

- name: "openbsd : setup xray vpn"
  hosts: vless, vmess, trojan, all_vpns
  roles:
    - role: xray
  tags:
    - xray

- name: "openbsd : setup sshvpn"
  hosts: sshvpn, all_vpns
  roles:
    - role: sshvpn
  tags:
    - sshvpn

- name: "openbsd : setup sshvpn"
  hosts: hysteria, all_vpns
  roles:
    - role: hysteria
  tags:
    - hysteria

- name: "openbsd : setup dns resolver with adblock and web interface"
  hosts: all
  roles:
    - role: dns
  tags:
    - dns

- name: "openbsd : setup web interface for vpn clients"
  hosts: all
  roles:
    - role: web
  tags:
    - web
