- name: "template out config"
  ansible.builtin.template:
    src: ocserv.conf.j2
    dest: /var/vpns/ocserv/ocserv.conf

- name: "generate public, private key pair"
  ansible.builtin.shell: "openssl req -x509 -newkey rsa:4096 -keyout /var/vpns/ocserv/certs/server-key.pem -out /var/vpns/ocserv/certs/server-cert.pem -sha256 -days 3650 -nodes -subj /CN=example &>/dev/null"
