---
- name: "template out config"
  ansible.builtin.template:
    src: ocserv.conf.j2
    dest: /var/vpns/ocserv/ocserv.conf

- name: "template out nat rules in pf.conf"
  ansible.builtin.blockinfile:
    path: /etc/pf.conf
    create: true
    backup: true
    marker: "### {mark} - OCSERV - ANSIBLE ###"
    insertafter: "EOF"
    block: |
      # openconnect
      
      match out on {{ ansible_default_ipv4.interface }} from {{ ocserv_network | default("172.16.16.0/24") }} to any nat-to ({{ ansible_default_ipv4.interface }})
      match in on {{ ansible_default_ipv4.interface }} from any to {{ ocserv_network | default("172.16.16.0/24") }} nat-to ({{ ansible_default_ipv4.interface }})
      
- name: "generate public, private key pair"
  ansible.builtin.shell: "openssl req -x509 -newkey rsa:4096 -keyout /var/vpns/ocserv/certs/server-key.pem -out /var/vpns/ocserv/certs/server-cert.pem -sha256 -days 3650 -nodes -subj /CN=example &>/dev/null"
