---
- name: "ocserv user management"
  ocserv:
    users: "{{ all_users|default([]) + ocserv_users|default([]) }}"
  register: ocserv_user_pass_dict

- name: "add ocserv user password pair to list"
  set_fact:
    user_pass_list: "{{ user_pass_list|default([]) + [ocserv_user_pass_dict] }}"
  notify:
    - debug_passwords
    - restart_ocserv

