---
- name: "ocserv user management"
  ocserv:
    users: "{{ all_users|default([]) + ocserv_users|default([]) }}"
  register: ocserv_user_pass_dict
  notify:
    - ocserv_debug_passwords
    - restart_ocserv
