---
- name: "ocserv user management"
  ocserv:
    users: "{{ all_users|default([]) + ocserv_users|default([]) }}"
  notify:
    - restart_ocserv
#  no_log: true
  register: ocserv_user_pass_dict

- name: "make temp dir"
  ansible.builtin.file:
    path: /var/reactance/.temp/
    state: directory

- name: "add ocserv user password pair to dict"
  ansible.builtin.copy:
    content: "{{ ocserv_user_pass_dict['msg']|default({}) | to_json }}"
    dest: /var/reactance/.temp/ocserv_user_pass_dict
