---
- name: "ocserv user management"
  ocserv:
    users: "{{ all_users|default([]) + ocserv_users|default([]) }}"
  notify:
    - restart_ocserv
#  no_log: true
  register: ocserv_user_pass_dict

- name: "read from user pass file"
  ansible.builtin.slurp:
    src: /var/reactance/.user_pass_dict
  register: user_pass_dict_contents

- name: "add ocserv user password pair to dict"
  ansible.builtin.copy:
    content: "{{ (user_pass_dict_contents.content|b64decode|from_json | combine(ocserv_user_pass_dict['msg']|default({}), recursive=true, list_merge='append')) | to_json }}"
    dest: /var/reactance/.user_pass_dict
