---
- name: "make configuration directory"
  ansible.builtin.file:
    path: /etc/vpns/ocserv
    owner: _ocserv
    group: root
    mode: 0700
    state: directory

- name: "install ocserv"
  community.general.openbsd_pkg:
    name: ocserv--
    state: present

- name: "template out config"
  ansible.builtin.template:
    src: ocserv.conf.j2
    dest: /etc/vpns/ocserv/ocserv.conf.j2

- name: "template out init script"
  ansible.builtin.template:
    src: ocserv.rc.j2
    dest: /etc/vpns/ocserv/ocserv.rc

- name: "install init script"
  ansible.builtin.shell: "install -m 755 -g bin /etc/vpns/ocserv/ocserv.rc /etc/rc.d/ocserv && rm -rf /etc/vpns/ocserv/ocserv.rc"
  notify:
    - start_ocserv
