Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "obsd74"
    vm1.vm.hostname = "box1"
    vm1.ssh.shell = "sh -l"
    vm1.ssh.private_key_path = "/home/dev/.ssh/vagrantbox"
    vm1.vm.network "private_network", ip: "172.16.0.2", libvirt__network_name: "vagrantbox_net"
    vm1.vm.synced_folder ".", "/vagrant", disabled: true
    vm1.vm.provider "libvirt" do |lv|
      lv.cpus = 1
      lv.memory = 1024
    end
  end
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "obsd74"
    vm1.vm.hostname = "box2"
    vm1.ssh.shell = "sh -l"
    vm1.ssh.private_key_path = "/home/dev/.ssh/vagrantbox"
    vm1.vm.network "private_network", ip: "172.16.0.2", libvirt__network_name: "vagrantbox_net"
    vm1.vm.synced_folder ".", "/vagrant", disabled: true
    vm1.vm.provider "libvirt" do |lv|
      lv.cpus = 1
      lv.memory = 1024
    end
  end
end
