---
- name: "Check if xray is already installed"
  ansible.builtin.stat:
    path: /var/reactance/xray
  register: xray_directory

- name: "Check if xray is configured"
  ansible.builtin.stat:
    path: /var/reactance/xray/etc/config.json
  register: xray_config

- name: "Install xray if directory doesn't exist"
  ansible.builtin.include_tasks: install_xray_openbsd.yaml
  when:  xray_directory.stat.exists == false and ansible_distribution|lower == "openbsd"

- name: "Install xray if directory doesn't exist"
  ansible.builtin.include_tasks: install_xray_alpine.yaml
  when:  xray_directory.stat.exists == false and ansible_distribution|lower == "alpine"

- name: "Configure xray"
  ansible.builtin.include_tasks: configure_xray.yaml
  when: xray_config.stat.exists == false

- name: "Create xray users"
  ansible.builtin.include_tasks: create_users_xray.yaml
