---
# generate keypair, needed for config
- name: "generate private, public keypair for xtls-reality"
  ansible.builtin.shell: "/var/vpns/xray/bin/xray x25519 | awk '{ print $3 }' | tr '\n' ','"
  register: keypair

- name: "set private key as var"
  ansible.builtin.set_fact:
    private_key: "{{ (keypair.stdout | split(',')).0 }}"
    public_key: "{{ (keypair.stdout | split(',')).1 }}"

- name: "write public key to file"
  ansible.builtin.copy:
    content: "{{ public_key }}"
    dest: "/var/vpns/xray/public_key"

- name: "write private key to file"
  ansible.builtin.copy:
    content: "{{ private_key }}"
    dest: "/var/vpns/xray/private_key"

- name: "template out config and init script"
  ansible.builtin.template:
    src: config.json.j2
    dest: "/var/vpns/xray/etc/config.json"
