---
# xray may be restarted multiple times. Is inefficient. But no simple way of going around it.

- name: "vless user management"
  xray:
    users: "{{ all_users|default([]) + vless_users|default([]) }}"
    protocol: vless
  when: inventory_hostname in (groups['vless']|default([]))
  register: vless_user_pass_dict
  notify:
    - vless_debug_passwords
    - restart_xray


- name: "vmess user management"
  xray:
    users: "{{ all_users|default([]) + vmess_users|default([]) }}"
    protocol: vmess
  when: inventory_hostname in (groups['vmess']|default([]))
  register: vmess_user_pass_dict
  notify:
    - vmess_debug_passwords
    - restart_xray

- name: "trojan user management"
  xray:
    users: "{{ all_users|default([]) + trojan_users|default([]) }}"
    protocol: trojan
  when: inventory_hostname in (groups['trojan']|default([]))
  register: trojan_user_pass_dict
  notify: 
    - trojan_debug_passwords
    - restart_xray
