---
# xray may be restarted multiple times. Is inefficient. But no simple way of going around it.

- name: "vless user management"
  xray:
    users: "{{ all_users|default([]) + vless_users|default([]) }}"
    protocol: vless
  when: inventory_hostname in (groups['vless']|default([])) + (groups['all_vpns']|default([]))
  register: vless_user_pass_dict
  notify: 
    - debug_passwords
    - restart_xray

- name: "vmess user management"
  xray:
    users: "{{ all_users|default([]) + vmess_users|default([]) }}"
    protocol: vmess
  when: inventory_hostname in (groups['vmess']|default([])) + (groups['all_vpns']|default([]))
  register: vmess_user_pass_dict
  notify: 
    - debug_passwords
    - restart_xray

- name: "trojan user management"
  xray:
    users: "{{ all_users|default([]) + trojan_users|default([]) }}"
    protocol: trojan
  when: inventory_hostname in (groups['trojan']|default([])) + (groups['all_vpns']|default([]))
  register: trojan_user_pass_dict
  notify: 
    - debug_passwords
    - restart_xray

- name: "add xray user password pair to list"
  set_fact:
    user_pass_list: "{{ user_pass_list|default([]) + [vless_user_pass_dict['msg']|default([])] + [vmess_user_pass_dict['msg']|default([])] + [trojan_user_pass_dict['msg']|default([])] }}"
