---
# xray may be restarted multiple times. Is inefficient. But no simple way of going around it.

- name: "vless user management"
  xray:
    users: "{{ all_users|default([]) + vless_users|default([]) }}"
    protocol: vless
  when: inventory_hostname in (groups['vless']|default([])) + (groups['all_vpns']|default([]))
  register: vless_user_pass_dict
  no_log: true
  notify: 
    - restart_xray

- name: "vmess user management"
  xray:
    users: "{{ all_users|default([]) + vmess_users|default([]) }}"
    protocol: vmess
  when: inventory_hostname in (groups['vmess']|default([])) + (groups['all_vpns']|default([]))
  register: vmess_user_pass_dict
  no_log: true
  notify: 
    - restart_xray

- name: "trojan user management"
  xray:
    users: "{{ all_users|default([]) + trojan_users|default([]) }}"
    protocol: trojan
  when: inventory_hostname in (groups['trojan']|default([])) + (groups['all_vpns']|default([]))
  register: trojan_user_pass_dict
  no_log: true
  notify: 
    - restart_xray

- name: "read from user pass file"
  ansible.builtin.slurp:
    src: /var/reactance/.user_pass_dict
  register: user_pass_dict_contents

- name: "add ocserv user password pair to dict"
  ansible.builtin.copy:
    content: "{{ (user_pass_dict_contents.content|b64decode|from_json | combine(trojan_user_pass_dict['msg']|default({}), vmess_user_pass_dict['msg']|default({}), vless_user_pass_dict['msg']|default({}), recursive=true, list_merge='append')) | to_json }}"
    dest: /var/reactance/.user_pass_dict
