---
# xray may be restarted multiple times. Is inefficient. But no simple way of going around it.

- name: "vless user management"
  xray:
    users: "{{ all_users|default([]) + vless_users|default([]) }}"
    protocol: vless
  when: inventory_hostname in (groups['vless']|default([])) + (groups['all_vpns']|default([]))
  register: vless_user_pass_dict
  no_log: true
  notify: 
    - debug_passwords
    - restart_xray

- name: "vmess user management"
  xray:
    users: "{{ all_users|default([]) + vmess_users|default([]) }}"
    protocol: vmess
  when: inventory_hostname in (groups['vmess']|default([])) + (groups['all_vpns']|default([]))
  register: vmess_user_pass_dict
  no_log: true
  notify: 
    - debug_passwords
    - restart_xray

- name: "trojan user management"
  xray:
    users: "{{ all_users|default([]) + trojan_users|default([]) }}"
    protocol: trojan
  when: inventory_hostname in (groups['trojan']|default([])) + (groups['all_vpns']|default([]))
  register: trojan_user_pass_dict
  no_log: true
  notify: 
    - debug_passwords
    - restart_xray

- name: "add xray user password pair to dict"
  set_fact:
    xray_user_pass_dict: "{{ user_pass_dict|default({}) | combine(trojan_user_pass_dict['msg']|default({}), vmess_user_pass_dict['msg']|default({}), vless_user_pass_dict['msg']|default({}), recursive=true, list_merge='append') }}" 
  no_log: true

- name: "add xray usernames to list"
  set_fact:
    user_pass_list: "{{ user_pass_list|default([]) + trojan_user_pass_dict['msg'].keys()|default([]) + vmess_user_pass_dict['msg'].keys()|default([]) + vless_user_pass_dict['msg'].keys()|default([]) }}" 
  no_log: true
