---
- name: "generate private, public keypair for xtls-reality"
  ansible.builtin.shell: "xray x25519 | awk '{ print $3 }'"
  register: keypair

- name: "create public key file"
  ansible.builtin.file:
    path: "{{ vpns_dir }}/xray/public_key"
    state: file

- name: "write public key to file"
  ansible.builtin.copy:
    content: "{{ keypair.stdout | split('\n')[1]}}"

- name: "template out config"
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ vpns_dir }}/xray/config.json"
  notify:
    - start_xray
