---
- name: "Check if sshvpn is already installed"
  ansible.builtin.stat:
    path: /home/sshvpn
  register: sshvpn_directory
- name: "Setup sshvpn if directory doesn't exist"
  ansible.builtin.include_tasks: setup_sshvpn.yaml
  when:  sshvpn_directory.stat.exists == false
- name: "Create sshvpn users"
  ansible.builtin.include_tasks: create_users_sshvpn.yaml
