---
- name: "Create sshvpns user"
  ansible.builtin.user:
    name: sshvpn
    shell: /sbin/nologin
    home: /home/sshvpn

- name: "Create .ssh directory (if not exists)"
  ansible.builtin.file:
    path: /home/sshvpn/.ssh
    owner: sshvpn
    group: sshvpn
    mode: 700

- name: "Run user management script"
  include_tasks: create_users_sshvpn.yaml
