---
- name: restart_hysteria
  ansible.builtin.service:
    name: hysteria
    state: restarted
    enabled: true

- name: remove_hysteria_tempdir
  ansible.builtin.file:
    path: "{{ hysteria_tempdir.path }}"
    state: absent
 
- name: hysteria_debug_passwords
  ansible.builtin.debug:
    var: hysteria_user_pass_dict
