FROM alpine:latest

RUN apk add --no-cache ansible openssh-client \
        ca-certificates \
        git \
        openssh-client \
        openssl \
        py3-cryptography \
        py3-pip \
        py3-yaml \
        python3\
        rsync \
        sshpass \
        openssl-dev \
        python3-dev

CMD ["/bin/sh"]
