---
- name: "install unzip"
  community.general.openbsd_pkg:
    name: unzip--
    state: present

- name: "create temporary directory"
  ansible.builtin.tempfile:
    state: directory
    suffix: temp
  register: v2ray_tempdir

# - name: "retrieve version name"

- name: "download v2ray"
  ansible.builtin.get_url:
    url: "https://github.com/v2fly/v2ray-core/releases/download/v5.10.1/v2ray-openbsd-64.zip"
    dest: "{{ v2ray_tempdir.path }}/v2ray.zip"

- name: "unzip v2ray"
  ansible.builtin.shell: "unzip v2ray.zip"
  args:
    chdir: "{{ v2ray_tempdir.path }}"

- name: "Install v2ray"
  ansible.builtin.shell: "{{ item }}"
  loop:
    - "install -m 755 -g bin {{ v2ray_tempdir.path }}/v2ray /usr/local/bin/v2ray"
    - "install -d /usr/local/share/v2ray"

- name: "Install geoip.dat, geosite.dat files"
  ansible.builtin.shell: "install -m 755 -g bin {{ v2ray_tempdir.path }}/{{ item }} /usr/local/share/v2ray/{{ item }}"
  loop:
    - "geoip.dat"
    - "geosite.dat"

- name: "Generate TLS cert and key"
  ansible.builtin.shell: "/usr/local/bin/v2ray tls cert"
  register: v2ray_cert_key

- name: "template out init script"
  ansible.builtin.template:
    src: v2ray.rc.j2
    dest: /etc/vpns/v2ray/v2ray.rc

- name: "install init script"
  ansible.builtin.shell: "install -m 755 -g bin /etc/vpns/v2ray/v2ray.rc /etc/rc.d/v2ray && rm -rf /etc/vpns/v2ray/v2ray.rc"
  notify:
    - start_v2ray

