---
- name: "make temporary directory on localhost"
  delegate_to: localhost
  ansible.builin.tempfile:
    prefix: reactance
    state: directory
  register: hugo_tmp

- name: "copy specific folders to hugo_tmp for each user"
  delegate_to: localhost
  ansible.posix.synchronize:
    src: utils/web
    dest: "{{ hugo_tmp }}/{{ item.key }}"
  rsync_opts:
    - "{{ '--exclude=utils/web/content/docs/ocserv' if 'ocserv' in {{item}} }}"
    - "{{ '--exclude=utils/web/content/docs/xray' if 'xray' in {{item}} }}"
    - "{{ '--exclude=utils/web/content/docs/sshvpn' if 'sshvpn' in {{item}} }}"
  loop: user_pass_dict

- name: "template out files for different languages"
  ansible.builtin.include_tasks: template_files.yaml
  vars:
    - content_dir: "{{ item }}"
  loop:
    - 'content.en'
    - 'content.ligma'

- name: "copy hugo_build.sh to temp dir"
  delegate_to: localhost
  ansible.builtin.copy:
    src: utils/hugo_build.sh
    dest: "{{ hugo_tmp }}/hugo_build.sh"

- name: "build hugo sites"
  delegate_to: localhost
  ansible.builtin.shell: "cd {{ hugo_tmp }} && sh ./hugo_build.sh"

- name: "copy sites"
  ansible.posix.synchronize:
    src: "{{ hugo_tmp }}/" # this will only copy contents
    dest: "/var/www/reactance/"
