---
- name: "copy ocserv cert"
  ansible.builtin.copy:
    remote_src: true
    src: "/var/reactance/ocserv/certs/{{ item }}-cert.pem"
    dest:  "/var/www/reactance/{{ item }}/{{ item }}-User-Certificate.pem"
    owner: www
    group: daemon
  loop: "{{ (ocserv_user_pass_dict_contents.content|default('e30K')|b64decode|from_json).keys()}}"

- name: "copy ocserv key"
  ansible.builtin.copy:
    remote_src: true
    src: "/var/reactance/ocserv/certs/{{ item }}-key.pem"
    dest:  "/var/www/reactance/{{ item }}/{{ item }}-User-Key.pem"
    owner: www
    group: daemon
  loop: "{{ (ocserv_user_pass_dict_contents.content|default('e30K')|b64decode|from_json).keys()}}"

- name: "copy ocserv p12 cert"
  ansible.builtin.copy:
    remote_src: true
    src: "/var/reactance/ocserv/certs/{{ item }}.p12"
    dest:  "/var/www/reactance/{{ item }}/{{ item }}-Certificate-Android.p12"
    owner: www
    group: daemon
  loop: "{{ (ocserv_user_pass_dict_contents.content|default('e30K')|b64decode|from_json).keys()}}"

