---
- name: "Create vpns user"
  ansible.builtin.user:
    name: _vpn
    create_home: no
    comment: Project VPN user
    state: present
    shell: /sbin/nologin
  notify: restart_notification

- name: "Create root directory of vpn services"
  ansible.builtin.file:
    path: /var/reactance/
    state: directory
    owner: _vpn
    group: _vpn
    mode:  0755

