---
- name: "add root pubkeys"
  ansible.builtin.include_tasks: add_pubkeys.yaml

- name: "run pre execution checks"
  ansible.builtin.include_tasks: pre_execution_checks.yaml

- name: "run base setup"
  ansible.builtin.include_tasks: base_setup.yaml

- name: "template out user expiration script and cronjob"
  ansible.builtin.include_tasks: setup_user_expiration.yaml
