---
- name: "Create vpns user"
  ansible.builtin.user:
    name: _vpn
    comment: Project VPN user
    state: present
    shell: /sbin/nologin

- name: "Create root directory of vpn services"
  ansible.builtin.file:
    path: /var/vpns/
    state: directory
    owner: _vpn
    group: nogroup
    mode:  0755

- name: "Setup user expiry"
  include_tasks: user_expiry_setup.yaml
