---
- name: "Create vpns user"
  ansible.builtin.user:
    name: _vpn
    create_home: no
    comment: Project VPN user
    state: present
    shell: /sbin/nologin

- name: "Create root directory of vpn services"
  ansible.builtin.file:
    path: /var/vpns/
    state: directory
    owner: _vpn
    group: nogroup
    mode:  0755

- name: "Setup user expiry"
  include_tasks: user_expiry_setup.yaml

- name: "templating out ip forwarding rules in sysctl.conf"
  ansible.builtin.blockinfile:
    path: /etc/sysctl.conf
    create: true
    backup: true
    marker: "### IP Forwarding - ANSIBLE ###"
    insertafter: "EOF"
    block: |
      net.inet.ip.forwarding=1
      net.inet6.ip6.forwarding=1
