---
- name: "Create vpns user"
  ansible.builtin.user:
    name: _vpn
    create_home: no
    comment: Project VPN user
    state: present
    shell: /sbin/nologin

- name: "Create root directory of vpn services"
  ansible.builtin.file:
    path: /var/vpns/
    state: directory
    owner: _vpn
    group: nogroup
    mode:  0755

- name: "Setup user expiry"
  include_tasks: user_expiry_setup.yaml

- name: "template out sysctl.conf"
  ansible.builtin.template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - restart_notification
