---
- name: "Template out user expiration script and daily.local"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner }}"
  loop:
    - src: daily.local.j2
      dest: /etc/daily.local
      mode: "0644"
      owner: root
    - src: user_expiration_control.py.j2
      dest: /var/reactance/.user_expiration_control.py
      mode: "0700"
      owner: _vpn

- name: "write user expiration information to file"
  user_expiration:
    users: "{{ all_users|default([]) + ocserv_users|default([]) + vless_users|default([]) + vmess_users|default([]) + trojan_users|default([]) + sshvpn_users|default([]) + hysteria_users|default([]) }}"

- name: "touch temporary user password json file"
  ansible.builtin.copy:
    content: "{}"
    dest: /var/reactance/.user_pass_dict
    owner: _vpn
    group: _vpn
    mode: 0600
