---
- name: start_ocserv
  ansible.builtin.service:
    name: ocserv
    state: restarted
    enabled: true

- name: remove_ocserv_tempdir
  ansible.builtin.file:
    path: "{{ ocserv_tempdir.path }}"
    state: absent
